routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Route::get('/dashboard', function () {
//     return view('dashboard');
// })->middleware(['auth'])->name('dashboard');

//auth route for both

Route::group(['middleware'=>['auth']],function(){
    Route::get('/dashboard','App\Http\controllers\DashboardController@index')->name
    ('dashboard');
    Route::get('/dashboard/myprofile','App\Http\controllers\DashboardController@profile')->name
    ('dashboard.myprofile');
});

Route::group(['middleware' => ['auth', 'role:user']], function() { 
    Route::get('/dashboard/newproject', 'App\Http\Controllers\DashboardController@newproject')->name('dashboard.newproject');
    Route::get('/dashboard/changepassword', 'App\Http\Controllers\DashboardController@changepassword')->name('dashboard.changepassword');
    Route::post('/change/password',   'App\Http\Controllers\UserController@changePassword')->name('profile.change.password');
});
Route::group(['middleware' => ['auth', 'role:manager|superadmin|user']], function() { 
   
    Route::get('/dashboard/myprojects', 'App\Http\Controllers\DashboardController@myprojects')->name('dashboard.myprojects');
});
Route::group(['middleware' => ['auth', 'role:manager|superadmin|user']], function() { 
    Route::get('/dashboard/users', 'App\Http\Controllers\DashboardController@users')->name('dash.users');

});


Route::resource('/dashboard/projects', 'App\Http\Controllers\ProjectController');

Route::resource('/dashboard/people', 'App\Http\Controllers\UserController');

require __DIR__.'/auth.php';

resources/views/partials/customers.blade.php
<div class="content">

    <a href="">
        <h1 class="title">{{ $person->name }}</h1>
    </a>
    <h5>{{ $person->name }}</h5>
    <h5>{{ $person->email }}</h5>
    <h5>{{ $person->phone }}</h5>

    <form method="post" action="{{ route('people.destroy', $person) }}">
        @csrf
        @method('delete')
        <div class="field is-grouped">
        @if (Auth::user()->hasRole('superadmin'))
            <div class="control">
                <a href="{{ route('people.edit', $person) }}" class="button is-info is-outlined">
                    Edit
                </a>
            </div>
            @endif
            @if (Auth::user()->hasRole('superadmin'))
            <div class="control">
                <button type="submit" class="button is-danger is-outlined">Delete</button>
            </div>
            @endif
        </div>
    </form>

</div>

resources/views/partials/errors.blade.php
@if ($errors->any())
    <div class="notification is-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

resources/views/partials/summary.blade.php
<div class="content">

    <a href="">
        <h4 class="title">{{ $project->name }}</h4>
    </a>
    <p>{!! nl2br(e($project->desc)) !!}</p>
    <img src="{{ Storage::url($project->image) }}"  width="320" height="240"  alt="" /><br>
    <p>{!! nl2br(e($project->git)) !!}</p>
    <video width="320" height="240" controls>
    <source src="{{ Storage::url($project->video) }}" >
    </video><br>
    <p><b>status:</b> {{ $project->status }}</p>
    <p><b>Posted:</b> {{ $project->created_at->diffForHumans() }}</p>
    <form method="post" action="{{ route('projects.destroy', $project) }}">
        @csrf
        @method('delete')
        <div class="field is-grouped">
        @if (Auth::user()->hasRole('superadmin|user'))
            <div class="control">
                <a href="{{ route('projects.edit', $project) }}" class="button is-info is-outlined">
                    Edit
                </a>
            </div>
            @endif
            @if (Auth::user()->hasRole('superadmin'))
            <div class="control">
                <button type="submit" class="button is-danger is-outlined">Delete</button>
            </div>
            @endif
        </div>
        <br>
    </form>
    <br>

</div>