routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Route::get('/dashboard', function () {
//     return view('dashboard');
// })->middleware(['auth'])->name('dashboard');

//auth route for both

Route::group(['middleware'=>['auth']],function(){
    Route::get('/dashboard','App\Http\controllers\DashboardController@index')->name
    ('dashboard');
    Route::get('/dashboard/myprofile','App\Http\controllers\DashboardController@profile')->name
    ('dashboard.myprofile');
});

Route::group(['middleware' => ['auth', 'role:user']], function() { 
    Route::get('/dashboard/newproject', 'App\Http\Controllers\DashboardController@newproject')->name('dashboard.newproject');
    Route::get('/dashboard/changepassword', 'App\Http\Controllers\DashboardController@changepassword')->name('dashboard.changepassword');
    Route::post('/change/password',   'App\Http\Controllers\UserController@changePassword')->name('profile.change.password');
});
Route::group(['middleware' => ['auth', 'role:manager|superadmin|user']], function() { 
   
    Route::get('/dashboard/myprojects', 'App\Http\Controllers\DashboardController@myprojects')->name('dashboard.myprojects');
});
Route::group(['middleware' => ['auth', 'role:manager|superadmin|user']], function() { 
    Route::get('/dashboard/users', 'App\Http\Controllers\DashboardController@users')->name('dash.users');

});


Route::resource('/dashboard/projects', 'App\Http\Controllers\ProjectController');

Route::resource('/dashboard/people', 'App\Http\Controllers\UserController');

require __DIR__.'/auth.php';

app/Models/Project.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    // use HasFactory;
    protected $fillable=['image','video','desc','git','status'];
   
        // protected $guarded = [];
    
}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Project;
use Illuminate\Support\Facades\Auth;

class ProjectController extends Controller
{
     /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
         $user = Auth::user();
        $projects = [];
        if($user->hasRole('user')){
            $projects =   Project::where("user_id",$user->id)->latest()->get();
        }else{

            $projects = Project::latest()->get();
        }
         
        // Pass project Collection to view
        return view('projects.index', compact('projects'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // Show create project form
        return view('projects.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

          $request->validate([
            'name' => 'required',
            'image' => 'required|image|mimes:jpg,png,jpeg,gif,svg|max:2048',
            'video' => 'required|mimes:mp4,ogx,oga,ogv,ogg,webm',
            'desc' =>'required',
            'git' =>'required|url',
            'status' =>'required'
        ]);
        $project = $request->all();
      //check if file exist 
      $path = $request->file('image')->store('public');
      $pathv = $request->file('video')->store('public');
        $project = new Project;
        $project->name = $request->name;
        $project->image = $path;
        $project->desc = $request->desc;
        $project->video = $pathv;
        $project->git = $request->git;
        $project->status = $request->status;
        $user = $request->user();
       

        $user->projects()->save($project);
  
        
        // Redirect the user to the created project woth a success notification
        return redirect(route('projects.show', $project))->with('notification', 'project created!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\project  $project
     * @return \Illuminate\Http\Response
     */
    public function show(Project $project)
    {

      
           // Pass current project to view
           return view('projects.show', compact('project'));
    }
  
    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function edit(Project $project)
    {

       
        return view('projects.edit', compact('project'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\project  $project
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Project $project)
    {


        
        // Validate projected form data
        $validated = $request->validate([
            'name' => 'required',
            'desc' =>'required',
            'git' =>'required|url',
            'status' =>'required'
        ]);

        if($request->hasFile('image')){
            $request->validate([
              'image' => 'required|image|mimes:jpg,png,jpeg,gif,svg|max:2048',
            ]);
            $path = $request->file('image')->store('public');
            $project->image = $path;
        }
        if($request->hasFile('video')){
            $request->validate([
                'video' => 'required|mimes:mp4,ogx,oga,ogv,ogg,webm',
            ]);
            $pathv = $request->file('video')->store('public');
            $project->video = $pathv;
        }
        $project->name = $request->name;
        $project->desc = $request->desc;
        $project->git = $request->git;
        $project->status = $request->status;


        // Update project with validated data
        $project->update($validated);

        // Redirect the user to the created project woth an updated notification
        return redirect(route('projects.show', $project))->with('notification', 'Project updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function destroy(Project $project)
    {
        // Delete the specified project
        $project->delete();

        // Redirect user with a deleted notification
        return redirect(route('projects.index'))->with('notification', '"' . $project->name .  '" deleted!');
    }
   
}

resources/views/projects/create.blade.php
@section('title', 'New Project')
@extends('layout')

@section('content')

<h1 class="title">Create a new project</h1>

<form method="post" action="{{ route('projects.store') }}" enctype="multipart/form-data">

    @csrf
    @include('partials.errors')
   <!-- project  name -->
    <div class="field">
        <label class="label">Project name</label>
        <div class="control">
            <input type="text" name="name" value="{{ old('name') }}" class="input" placeholder="project name" minlength="5" maxlength="100" required />
        </div>
    </div>
    <!-- image -->
    <div class="field">
   
    <strong>Project Image:</strong><br>
    <div class="control">
    <input type="file" name="image" class="form-control" placeholder="Post Title">
    </div>
    </div>
    <!-- video -->
    <div class="field">
    <strong>Project video:</strong>
    <div class="control">
        <input type="file" name="video" class="form-control" placeholder="Post Title">
    </div>
    </div>
      
    
    <!-- gitlink -->
    <div class="field">
        <label class="label">Git link</label>
        <div class="control">
            <input type="text" name="git" value="{{ old('git') }}" class="input" placeholder="git link" maxlength="100" required />
        </div>
    </div>

    <div class="field">
        <label class="label">description</label>
        <div class="control">
            <textarea name="desc" class="textarea" placeholder="desc" minlength="5" maxlength="2000" required rows="10">{{ old('desc') }}</textarea>
        </div>
    </div>

    <div class="field">
        <label class="label">Status</label>
        <div class="control">
            <div class="select">
                <select name="status" required>
                    <option value="" disabled selected>Select status</option>
                    <option value="active" {{ old('status') === 'active' ? 'selected' : null }}>Active</option>
                    <option value="incomplete" {{ old('status') === 'incomplete' ? 'selected' : null }}>Incomplete</option>
                    <option value="ongoing" {{ old('status') === 'ongoing' ? 'selected' : null }}>Ongoing</option>
                    <option value="stuck" {{ old('status') === 'stuck' ? 'selected' : null }}>Stuck</option>
                </select>
                
            </div>
        </div>
    </div>

    <div class="field">
        <div class="control">
            <button type="submit" class="button is-link is-outlined">Publish</button>
        </div>
    </div>

</form>

@endsection

resources/views/projects/edit.blade.php
@section('title', 'Edit project')
@section('action', route('projects.create'))
@extends('layout')

@section('content')

<h1 class="title">Edit: {{ $project->name }}</h1>

<form method="post" action="{{ route('projects.update', $project) }}">

    @csrf
    @method('patch')
    @include('partials.errors')
    <!-- project name -->
    <div class="field">
        <label class="label">Project name</label>
        <div class="control">
            <input type="text" name="name" value="{{ $project->name }}" class="input" placeholder="project name"  required />
        </div>
    </div>
    <!-- image -->
    <div class="field">
   
    <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Post video:</strong>
                 <input type="file" name="image" class="form-control" placeholder="Post Title">
            </div>
            <div class="form-group">
              <img src="{{ Storage::url($project->image) }}" height="200" width="200" alt="" />


            </div>
        </div>
    <!-- video -->
    <div class="field">
   
   <div class="col-xs-12 col-sm-12 col-md-12">
           <div class="form-group">
               <strong>Post video:</strong>
                <input type="file" name="image" class="form-control" placeholder="Post Title">
           </div>
           <video width="320" height="240" controls>
            <source src="{{ Storage::url($project->video) }}" >
            </video>

           </div>
       </div>
    <!-- git link -->
    <div class="field">
        <label class="label">Title</label>
        <div class="control">
            <input type="text" name="git" value="{{ $project->git}}" class="input" placeholder="git link"  maxlength="100" required />
        </div>
    </div>
    <!-- description -->
    <div class="field">
        <label class="label">Project description</label>
        <div class="control">
            <textarea name="desc" class="textarea" placeholder="desc" minlength="5" maxlength="2000" required rows="10">{{ $project->desc}}</textarea>
        </div>
    </div>

    <div class="field">
        <label class="label">Status</label>
        <div class="control">
            <div class="select">
                <select name="status" required>
                    <option value="" disabled selected>Select status</option>
                    <option value="active" {{ $project->active === 'active' ? 'selected' : null }}>Active</option>
                    <option value="incomplete" {{ $project->incomplete === 'incomplete' ? 'selected' : null }}>Incomplete</option>
                    <option value="ongoing" {{ $project->ongoing === 'ongoing' ? 'selected' : null }}>Ongoing</option>
                    <option value="stuck" {{ $project->status === 'stuck' ? 'selected' : null }}>Stuck</option>
                </select>
            </div>
        </div>
    </div>

    <div class="field">
        <div class="control">
            <button type="submit" class="button is-link is-outlined">Update</button>
        </div>
    </div>

</form>

@endsection

resources/views/projects/index.blade.php
@section('title', 'Home')
@extends('layout')

@section('content')

<!-- <div class="container"> -->
<div class="row">
  @foreach ($projects as $project)
  <div class="col">
    @include('partials.summary')
</div>
@endforeach
</div>
<!-- </div> -->



@endsection

resources/views/projects/show.blade.php
@section('name', $project->name)
@extends('layout')

@section('content')

@include('partials.summary')

@endsection