routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Route::get('/dashboard', function () {
//     return view('dashboard');
// })->middleware(['auth'])->name('dashboard');

//auth route for both

Route::group(['middleware'=>['auth']],function(){
    Route::get('/dashboard','App\Http\controllers\DashboardController@index')->name
    ('dashboard');
    Route::get('/dashboard/myprofile','App\Http\controllers\DashboardController@profile')->name
    ('dashboard.myprofile');
});

Route::group(['middleware' => ['auth', 'role:user']], function() { 
    Route::get('/dashboard/newproject', 'App\Http\Controllers\DashboardController@newproject')->name('dashboard.newproject');
    Route::get('/dashboard/changepassword', 'App\Http\Controllers\DashboardController@changepassword')->name('dashboard.changepassword');
    Route::post('/change/password',   'App\Http\Controllers\UserController@changePassword')->name('profile.change.password');
});
Route::group(['middleware' => ['auth', 'role:manager|superadmin|user']], function() { 
   
    Route::get('/dashboard/myprojects', 'App\Http\Controllers\DashboardController@myprojects')->name('dashboard.myprojects');
});
Route::group(['middleware' => ['auth', 'role:manager|superadmin|user']], function() { 
    Route::get('/dashboard/users', 'App\Http\Controllers\DashboardController@users')->name('dash.users');

});


Route::resource('/dashboard/projects', 'App\Http\Controllers\ProjectController');

Route::resource('/dashboard/people', 'App\Http\Controllers\UserController');

require __DIR__.'/auth.php';

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/people/changingpassword.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>@yield('title') - Laravel Blog</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.4/css/bulma.min.css">
</head>

<body>
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('users list') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <!-- form -->

                    <form action="{{route('profile.change.password')}}" method="post" class="needs-validation" novalidate enctype="multipart/form-data">
        @csrf         
        <div class="row ">
            <div class="col-md-12">
                <div class="main-card mb-3  card">
                    <div class="card-body">
                        <h4 class="card-title">
                            <h4>Change Password</h4>
                        </h4>
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group mt-3">
                                    <label for="current_password">Old password</label>
                                    <input type="password" name="current_password" class="form-control @error('current_password') is-invalid @enderror" required
                                        placeholder="Enter current password">
                                    @error('current_password')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                   
                                    @enderror
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group mt-3">
                                    <label for="new_password ">new password</label>
                                    <input type="password" name="password" class="form-control @error('password') is-invalid @enderror" required
                                        placeholder="Enter the new password">
                                    @error('password')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                   
                                    @enderror
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group mt-3">
                                    <label for="confirm_password">confirm password</label>
                                    <input type="password" name="confirm_password" class="form-control @error('confirm_password') is-invalid @enderror"required placeholder="Enter same password">
                                    @error('confirm_password')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                   
                                    @enderror
                                </div>
                            </div>
                            <div class="d-flex justify-content-first mt-4 ml-2">
                             

                                    <button type="submit" class="button is-link is-outlined"  id="formSubmit">Change Password</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>        
    </form>

                    <!-- end form -->
                   
                   
                </div>
            </div>
        </div>
    </div>
</x-app-layout>
</body>
</html>

resources/views/people/edit.blade.php
@section('title', 'Edit User')
@extends('layout')

@section('content')

<h1 class="title">Edit: {{ $person->name }}</h1>

<form method="post" action="{{ route('people.update', $person) }}">

    @csrf
    @method('patch')
    @include('partials.errors')

    <div class="field">
        <label class="label">Name</label>
        <div class="control">
            <input type="text" name="name" value="{{ $person->name }}" class="input" placeholder="name" minlength="5" maxlength="100" required />
        </div>
    </div>

    <div class="field">
        <label class="label">Phone</label>
        <div class="control">
            <input type="text" name="phone" value="{{ $person->phone }}" class="input" placeholder="Phone" minlength="5" maxlength="100" required />
        </div>
    </div>

  

    <div class="field">
        <div class="control">
            <button type="submit" class="button is-link is-outlined">Update</button>
        </div>
    </div>

</form>

@endsection

resources/views/people/index.blade.php
@section('title', 'Home')
@extends('layout')

@section('content')
<div class="container">
<div class="row">
@foreach ($people as $person)
<div class="col-sm">
    @include('partials.customers')
</div>
@endforeach
</div>
</div>
@endsection

resources/views/people/show.blade.php
@section('title', $person->name)
@extends('layout')

@section('content')

@include('partials.customers')

@endsection